# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stix N Stones Shop
email: stixnst0nes4healingbones@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are a growing local business who believes in spreading positivity and joy to the world through our art. Our mission is to help this world heal itself, one crystal at a time
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.stixnstones4healingbones.com" # the base hostname & protocol for your site
twitter_username: stixnstonesshop
instagram_username: stixnst0nes

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
